language: java
sudo: false
script: 
- mvn clean verify
- bcopy /home/travis/build/andresfqm2/ProyectoPoli/target/RestauranteAPPV2-1.0-SNAPSHOT.war C:\home\wildfly-8.2.0.Final\standalone\deployments\RestauranteAPPV2-1.0-SNAPSHOT.war
deploy:
provider: pages
skip-cleanup: true
github-token: $GITHUB_TOKEN
local_dir: build
on:
branch: master